# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: nc_tools - CNC/CAM GCode tools
email: 
description: > # this means to ignore newlines until "baseurl:"
  nc_tools GCode tools
baseurl: "/nc_tools" # the subpath of your site, e.g. /blog
url: "http://mythagel.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username: mythagel

# Build settings
markdown: kramdown
